[package]
name = "firerust"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "GNU General Public License v3.0"
authors = ["Daniel Dimbarre <contato@danieldimbarre.pl>"]
homepage = "https://github.com/danieldimbarre/Firerust.git"
repository = "https://github.com/danieldimbarre/Firerust.git"
description = "A simple library for Realtime Database of Firebase."

[dependencies]
